upstream identity_service {
    server identity-service:8001;
}

upstream moderation_service {
    server moderation-service:8002;
}

upstream chat_service {
    server chat-service:8003;
}

server {
    listen 8080;
    server_name _;

    client_max_body_size 20M;

    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # Identity Service — auth i stats
    location ~ ^/api/(register|login|logout|user|stats)$ {
        proxy_pass http://identity_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;
    }

    # Moderation Service — suspend MORA biti pre opšteg korisnik pravila
    location ~ ^/api/korisnik/[0-9]+/suspend$ {
        proxy_pass http://moderation_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;
    }

    location ~ ^/api/(uloga|korisnik) {
        proxy_pass http://identity_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;
    }

    location ~ ^/api/(prijava|sankcija) {
        proxy_pass http://moderation_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;
    }

    # Chat Service
    location ~ ^/api/(chat|poruka|datoteka) {
        proxy_pass http://chat_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;
    }
}
