global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: chat-service
    metrics_path: /metrics
    static_configs:
      - targets: ['chat-service:8003']

  - job_name: event-processor
    metrics_path: /metrics
    static_configs:
      - targets: ['event-processor:8010']

  - job_name: api-gateway
    metrics_path: /health
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: identity-service
    metrics_path: /api/health
    static_configs:
      - targets: ['identity-service:8001']

  - job_name: moderation-service
    metrics_path: /api/health
    static_configs:
      - targets: ['moderation-service:8002']
